### ISSUE TITLE
Uncaught exceptions in reaRate core functions

### ISSUE THREAD

**Issue by vlahm** [NEONScience/NEON-reaeration#2] opened 2018-08-21 18:59 UTC
I am unable to convert raw reaeration field data to rates, k600 values, etc. for all sites using the available tools.

The first error returned by def.format.reaeration(dataDir='API', site='all', fieldQ=TRUE) is "Reconcile duplicate external lab samples", thrown by streamQ::def.format.Q. After reconciliation, an unhandled exception occurs in def.format.reaeration, with the creation of pSaltConc. I worked around this using tryCatch to advance the loop when the exception was raised.

After getting def.format.reaeration to return successfully, I encountered two exceptions in def.calc.reaeration which are addressed in a pull request I just submitted. 

After addressing those exceptions, I got def.calc.reaeration to return without error, but outputDF returned by def.calc.reaeration contains no data, except for the siteID, eventID, and lossRateSF6 columns.

**Comment by kcawley** [comment] 2019-09-05 15:19
@vlahm Thanks for pointing this out. I'll try to take a look this week or early next week and figure out what the problem is.

**Comment by kcawley** [comment] 2019-09-11 21:56
@vlahm I just merged in some updates from a branch I had been working on. I didn't see a pull request from you to look at. Maybe try the code I just synced and then if it still isn't working send the pull request again and I'll take a look?

**Comment by vlahm** [comment] 2019-09-12 15:56
The pull request I mentioned was already merged a year ago ^_^. I'll follow up with you when I start working with these tools again. Likely in the next few months. Thanks!

**Closed as completed** 2019-09-12 16:20 UTC
Labels: bug
